#ifndef CUSTORMENUMERATORS_H_INCLUDED
#define CUSTORMENUMERATORS_H_INCLUDED

enum Transfer_Status{
    NOT_STARTED,
    IN_PROGRESS,
    COMPLETE,
    FAILED
};

#endif // CUSTORMENUMERATORS_H_INCLUDED
